[build]
  publish = "build"      # This is where your React build output goes
  command = "npm run build"  # Command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
